# Generated by Django 4.0.5 on 2022-06-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='dessert_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='maindish',
            name='main_dish_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sidedishes',
            name='side_dish_price',
            field=models.FloatField(),
        ),
    ]
