# Generated by Django 4.0.5 on 2022-06-18 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_alter_dessert_dessert_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='main_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.maindish'),
        ),
    ]
