# Generated by Django 4.0.5 on 2022-06-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_alter_order_main_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='main_dish',
            field=models.CharField(max_length=200),
        ),
    ]
