# Generated by Django 4.0.5 on 2022-06-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_order_order_value_alter_order_main_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='main_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.maindish'),
        ),
    ]
