# Generated by Django 4.0.5 on 2022-06-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_alter_order_main_dish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maindish',
            old_name='main_dish',
            new_name='dish',
        ),
    ]
