# Generated by Django 4.0.5 on 2022-06-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_rename_main_dish_maindish_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dessert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.dessert'),
        ),
    ]
